### GET all articles
GET http://localhost:3000/articles/

### GET one article
GET http://localhost:3000/articles/?id=5

### POST one article
POST http://localhost:3000/articles/
Content-Type: application/json

{
    "nom": "My first article",
    "description": "This is my first article",
    "prix": 10,
    "id_vendeur": 1,
    "photo": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"

}

