### GET member by id
GET http://localhost:3000/members/1

### GET all active members
GET http://localhost:3000/members/getActiveMembers

### GET all banned members
GET http://localhost:3000/members/getbannedMembers




### Add credit to a member (email, credits)
POST http://localhost:3000/members/addCredits
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be",
    "credits":25
}


### Add credit to a member (email, credits)
POST http://localhost:3000/members/addCredits
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be",
    "credits":25
}
### Remove credit to a member (email, credits)
POST http://localhost:3000/members/removeCredits
Content-Type: application/json

{    
    "email":"rayan.abarkan@student.vinci.be",
    "credits":25
}





### Grant a ban members (mail)
PUT http://localhost:3000/members/:email/promoteOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}

### Revoke an active members (mail)
PUT http://localhost:3000/members/:email/demoteOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}



### UnBan a members (mail)
PUT http://localhost:3000/members/:email/unbanOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}

###  Ban a members (mail)
PUT http://localhost:3000/members/:email/banOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}