### GET member by id
GET http://localhost:3000/members/1

### GET all admin members
GET http://localhost:3000/members/getAdminMembers


### GET all active members
GET http://localhost:3000/members/getActiveMembers

### GET all banned members
GET http://localhost:3000/members/getbannedMembers




### Add credit to a member (id_member, credits)
POST http://localhost:3000/members/addCredits
Content-Type: application/json

{
    "id_member":3,
    "credits":25
}


### Add credit to a member (id_member, credits)
POST http://localhost:3000/members/addCredits
Content-Type: application/json

{
    "id_member": 3,
    "credits":25
}
### Remove credit to a member (id_member, credits)
POST http://localhost:3000/members/removeCredits
Content-Type: application/json

{    
    "id_member":3,
    "credits":25
}





### Grant a ban members (mail)

POST http://localhost:3000/members/promoteOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}

### Revoke an active members (mail)

POST http://localhost:3000/members/demoteOne
Content-Type: application/json

{
    "email":"rayan.abarkan@student.vinci.be"
}



### UnBan a members (mail)
POST http://localhost:3000/members/unbanOne
Content-Type: application/json

{    
    "email":"olivier.bogearts@student.vinci.be"
}

###  Ban a members (mail)
POST http://localhost:3000/members/banOne
Content-Type: application/json

{    
    "email":"olivier.bogearts@student.vinci.be"
}